import type { Metadata } from "next";
import "./globals.css";
import "./style.css";



export const metadata: Metadata = {
  title: "Shahriar Rahman Niloy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
